spring.application.name=aula08

spring.datasource.url=jdbc:postgresql://servidordaniel.postgres.database.azure.com:5432/cti_provedor?sslmode=require
spring.datasource.username=senai26
spring.datasource.password=D@n100455

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


